import { useEffect, useRef, useState } from 'react'
import type { FunGameProps } from './types'
import { useSound } from '../hooks/useSound'
import DifficultySelector from '../components/DifficultySelector'
import Ltr from '../components/Ltr'

type Difficulty = 'easy' | 'medium' | 'hard'

const CLUES: Record<Difficulty, number> = { easy: 40, medium: 32, hard: 26 }

const DIFFICULTY_OPTIONS: { id: Difficulty; icon: string; label: string }[] = [
  { id: 'easy', icon: '🟢', label: 'קל' },
  { id: 'medium', icon: '🟡', label: 'בינוני' },
  { id: 'hard', icon: '🔴', label: 'קשה' },
]

function shuffle<T>(arr: T[]): T[] {
  const a = [...arr]
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[a[i], a[j]] = [a[j], a[i]]
  }
  return a
}

function isValidPlacement(grid: number[][], row: number, col: number, val: number): boolean {
  for (let i = 0; i < 9; i++) {
    if (grid[row][i] === val || grid[i][col] === val) return false
  }
  const boxRow = Math.floor(row / 3) * 3
  const boxCol = Math.floor(col / 3) * 3
  for (let r = boxRow; r < boxRow + 3; r++) {
    for (let c = boxCol; c < boxCol + 3; c++) {
      if (grid[r][c] === val) return false
    }
  }
  return true
}

/** Randomized backtracking fill - fast in practice for 9x9 Sudoku. This is a
    casual family game rather than a puzzle-logic app, so puzzles are
    generated by removing cells from a valid solved grid without a
    uniqueness pass (which most simple/casual Sudoku implementations skip) -
    every puzzle is solvable and every clue is correct, just not guaranteed
    to have exactly one solution the way a strict Sudoku app would promise. */
function generateSolvedGrid(): number[][] {
  const grid: number[][] = Array.from({ length: 9 }, () => Array(9).fill(0))
  function fill(pos: number): boolean {
    if (pos === 81) return true
    const row = Math.floor(pos / 9)
    const col = pos % 9
    for (const val of shuffle([1, 2, 3, 4, 5, 6, 7, 8, 9])) {
      if (isValidPlacement(grid, row, col, val)) {
        grid[row][col] = val
        if (fill(pos + 1)) return true
        grid[row][col] = 0
      }
    }
    return false
  }
  fill(0)
  return grid
}

function makePuzzle(difficulty: Difficulty) {
  const solution = generateSolvedGrid()
  const cellsToRemove = 81 - CLUES[difficulty]
  const positions = shuffle(Array.from({ length: 81 }, (_, i) => i)).slice(0, cellsToRemove)
  const puzzle = solution.map((row) => [...row])
  for (const pos of positions) puzzle[Math.floor(pos / 9)][pos % 9] = 0
  return { solution, puzzle }
}

export default function SudokuGame({ onFinish }: FunGameProps) {
  const { play } = useSound()
  const [difficulty, setDifficulty] = useState<Difficulty | null>(null)
  const [solution, setSolution] = useState<number[][]>([])
  const [board, setBoard] = useState<number[][]>([])
  const [fixed, setFixed] = useState<boolean[][]>([])
  const [selected, setSelected] = useState<[number, number] | null>(null)
  const [hintsUsed, setHintsUsed] = useState(0)
  const [mistakes, setMistakes] = useState(0)
  const [seconds, setSeconds] = useState(0)
  const [finished, setFinished] = useState(false)
  const finishedRef = useRef(false)

  useEffect(() => {
    if (!difficulty || finished) return
    const t = window.setInterval(() => setSeconds((s) => s + 1), 1000)
    return () => window.clearInterval(t)
  }, [difficulty, finished])

  const startGame = (d: Difficulty) => {
    const { solution: sol, puzzle } = makePuzzle(d)
    setSolution(sol)
    setBoard(puzzle.map((r) => [...r]))
    setFixed(puzzle.map((row) => row.map((v) => v !== 0)))
    setSelected(null)
    setHintsUsed(0)
    setMistakes(0)
    setSeconds(0)
    setFinished(false)
    finishedRef.current = false
    setDifficulty(d)
  }

  const isComplete = (b: number[][]) => b.every((row, r) => row.every((v, c) => v === solution[r][c]))

  const finishGame = (finalHints: number, finalMistakes: number) => {
    if (finishedRef.current) return
    finishedRef.current = true
    setFinished(true)
    const timeBonus = Math.max(0, 600 - seconds)
    const correct = Math.max(1, 81 - finalHints * 2 - finalMistakes + Math.floor(timeBonus / 30))
    onFinish({ correct, total: 81 })
  }

  const placeNumber = (val: number) => {
    if (!selected || finished) return
    const [r, c] = selected
    if (fixed[r][c]) return
    const nextBoard = board.map((row) => [...row])
    nextBoard[r][c] = val
    setBoard(nextBoard)
    if (solution[r][c] === val) {
      play('correct')
      if (isComplete(nextBoard)) finishGame(hintsUsed, mistakes)
    } else {
      play('wrong')
      setMistakes((m) => m + 1)
    }
  }

  const clearCell = () => {
    if (!selected || finished) return
    const [r, c] = selected
    if (fixed[r][c]) return
    const nextBoard = board.map((row) => [...row])
    nextBoard[r][c] = 0
    setBoard(nextBoard)
  }

  const useHint = () => {
    if (!selected || finished) return
    const [r, c] = selected
    if (fixed[r][c] || board[r][c] === solution[r][c]) return
    const nextBoard = board.map((row) => [...row])
    nextBoard[r][c] = solution[r][c]
    setBoard(nextBoard)
    const nextHints = hintsUsed + 1
    setHintsUsed(nextHints)
    play('click')
    if (isComplete(nextBoard)) finishGame(nextHints, mistakes)
  }

  if (!difficulty) {
    return <DifficultySelector title="🧩 סודוקו" subtitle="בחרו רמת קושי" options={DIFFICULTY_OPTIONS} onSelect={startGame} />
  }

  return (
    <div className="mx-auto max-w-md">
      <div className="mb-3 flex items-center justify-between px-1 font-fun text-sm font-extrabold">
        <span className="rounded-full bg-sky-100 px-3 py-1 text-sky-600">
          <Ltr>
            ⏱️ {Math.floor(seconds / 60)}:{String(seconds % 60).padStart(2, '0')}
          </Ltr>
        </span>
        <span className="rounded-full bg-candy-100 px-3 py-1 text-candy-600">❌ {mistakes}</span>
        <span className="rounded-full bg-sunny-100 px-3 py-1 text-sunny-600">💡 {hintsUsed}</span>
      </div>

      <div className="grid grid-cols-9 gap-[2px] rounded-xl2 bg-ink/20 p-1 shadow-card" dir="ltr">
        {board.map((row, r) =>
          row.map((val, c) => {
            const isSelected = selected?.[0] === r && selected?.[1] === c
            const isFixedCell = fixed[r][c]
            const boxShade = (Math.floor(r / 3) + Math.floor(c / 3)) % 2 === 0
            return (
              <button
                key={`${r}-${c}`}
                onClick={() => setSelected([r, c])}
                disabled={isFixedCell}
                aria-label={`תא שורה ${r + 1} עמודה ${c + 1}${val ? `, ערך ${val}` : ', ריק'}`}
                className={`grid aspect-square place-items-center text-sm font-extrabold sm:text-base ${
                  isSelected ? 'bg-grape-200' : boxShade ? 'bg-white' : 'bg-sky-50'
                } ${isFixedCell ? 'text-ink' : 'text-grape-600'}`}
              >
                {val || ''}
              </button>
            )
          })
        )}
      </div>

      <div className="mt-4 grid grid-cols-5 gap-2">
        {[1, 2, 3, 4, 5, 6, 7, 8, 9].map((n) => (
          <button
            key={n}
            onClick={() => placeNumber(n)}
            className="rounded-xl2 bg-white py-3 font-fun text-lg font-extrabold text-ink shadow-card card-outline btn-pressable"
          >
            {n}
          </button>
        ))}
        <button
          onClick={clearCell}
          aria-label="נקו תא"
          className="rounded-xl2 bg-candy-100 py-3 font-fun text-lg font-extrabold text-candy-700 shadow-card card-outline btn-pressable"
        >
          ✕
        </button>
      </div>

      <button onClick={useHint} className="mt-3 w-full rounded-full bg-sunny-400 px-5 py-2.5 font-fun text-sm font-extrabold text-ink shadow-card btn-pressable">
        💡 רמז
      </button>

      {finished && (
        <p className="mt-4 text-center font-fun text-lg font-extrabold text-grass-600">🎉 פתרתם את הסודוקו!</p>
      )}
    </div>
  )
}
